# Generated by Django 5.2.2 on 2025-06-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=100, unique=True, verbose_name='区域码')),
                ('name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('shipping_address', models.TextField(verbose_name='送货地址')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=100, verbose_name='物料编号')),
                ('material_description', models.CharField(max_length=255, verbose_name='物料描述')),
                ('outer_box_date', models.DateField(verbose_name='外箱日期')),
                ('batch_number', models.CharField(max_length=100, verbose_name='批次')),
                ('specification', models.CharField(max_length=100, verbose_name='规格')),
                ('packaging_line', models.CharField(blank=True, max_length=100, null=True, verbose_name='包装线')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='客户')),
            ],
        ),
    ]
