# Generated by Django 5.2.2 on 2025-06-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='区域码'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='api.customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='packaging_line',
            field=models.CharField(default='', max_length=50, verbose_name='包装线'),
        ),
        migrations.CreateModel(
            name='ProductionTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time_str', models.CharField(max_length=4, verbose_name='开始时间 (HHMM)')),
                ('end_time_str', models.CharField(max_length=4, verbose_name='结束时间 (HHMM)')),
                ('quantity', models.IntegerField(verbose_name='箱数/托盘数')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_time_slots', to='api.shipment', verbose_name='所属流向记录')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
