# Generated by Django 5.2.2 on 2025-06-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='production_date_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='生产日期码'),
        ),
    ]
