# Generated by Django 5.2.2 on 2025-06-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shipment_production_date_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productiontimeslot',
            name='quantity',
        ),
    ]
