# Generated by Django 5.2.2 on 2025-06-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_productiontimeslot_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, null=True, verbose_name='发货日期'),
        ),
    ]
